#!/usr/bin/env python3
"""
Generate SQL INSERT statements for Hizashi Sách 02 (Phone) → hizashi_db.

Usage:
    python3 scripts/gen_sql.py
    # Output: output/load_v1.2.sql
    # Run:  PGPASSWORD=admin123 psql -h localhost -U admin -d hizashi_db -f output/load_v1.2.sql

Defaults (sửa trong CONFIG nếu cần):
    tenant_id   = NULL
    created_by  = 'system'
    is_system   = true, is_public = true
    access_level: rule_01..03 = 'free'; rule_04..60 = 'paid'

Schema dùng (tham chiếu _shared/db.sql, 175 tables):
    curricula → curriculum_node (flat) → curriculum_node_content (junction)
    conversations + conversation_lines (good/bad/variant + key_phrases is_single_line=true)
    questions + questions_answers + question_sets + question_set_questions + content_questions
    vocabulary (dedup theo kanji unique)

Re-run: TRUNCATE các bảng trước, hoặc DELETE WHERE created_by='system' AND is_system=true.
"""
import json
import re
from pathlib import Path
from collections import OrderedDict

# ─── CONFIG ───────────────────────────────────────────────────────────
ROOT = Path(__file__).parent.parent
NOI_DUNG = ROOT / "nội_dung"
OUTPUT = ROOT / "output" / "load_v1.2.sql"

CONFIG = {
    "tenant_id": None,           # 'hizashi' if multi-tenant
    "created_by": "system",
    "is_system": True,
    "is_public": True,
    "free_rules": {1, 2, 3},     # rule_01..03 = free
    "curriculum_title": "Điện thoại Công Việc",
    "curriculum_title_jp": "電話応対",
    "level": "BJT-J3",
    "type": "phone",
    "category": "phone_scenarios",
    "qset_name": "BJT Practice — Sách 02 Phone",
}

# Difficulty map BJT level → 1..6
DIFF_MAP = {"J5": 1, "J4": 2, "J3": 3, "J2": 4, "J1": 5, "J1+": 6}

# ─── HELPERS ──────────────────────────────────────────────────────────

def esc(s):
    """Escape SQL string. Returns NULL if None."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def esc_bool(b):
    return "true" if b else "false"


def esc_jsonb(obj):
    if obj is None:
        return "NULL"
    return esc(json.dumps(obj, ensure_ascii=False)) + "::jsonb"


def parse_rule_md(md_path):
    """Parse rule.md to extract câu chốt (JP) and vocab table."""
    text = md_path.read_text(encoding="utf-8")

    # Câu chốt: under "## 🎯 Câu chốt" heading until next ##
    chot_match = re.search(r"##\s*🎯\s*Câu chốt\s*\n(.*?)(?=\n##|\Z)", text, re.DOTALL)
    chot_jp = None
    if chot_match:
        # Extract JP between 「...」 in the blockquote
        block = chot_match.group(1)
        m = re.search(r"「(.+?)」", block, re.DOTALL)
        if m:
            chot_jp = m.group(1).strip()

    # Vocab table: under "## 📚 Vocab" heading
    vocab_match = re.search(r"##\s*📚\s*Vocab\s*\n(.*?)(?=\n##|\Z)", text, re.DOTALL)
    vocabs = []
    if vocab_match:
        for line in vocab_match.group(1).split("\n"):
            if "|" not in line:
                continue
            parts = [p.strip() for p in line.split("|") if p.strip()]
            if len(parts) >= 3 and not parts[0].startswith("-") and parts[0] not in ("漢字", "Tiếng Nhật"):
                kanji, yomi, meaning = parts[0], parts[1], parts[2]
                if "---" in kanji or kanji == "":
                    continue
                vocabs.append((kanji, yomi, meaning))

    return chot_jp, vocabs


def find_rules():
    """Return ordered list of (rule_num, phan, json_path, md_path, data)."""
    rules = []
    for phan_dir in sorted(NOI_DUNG.glob("phần_*")):
        for rule_dir in sorted(phan_dir.glob("rule_*")):
            json_p = rule_dir / "conversation.json"
            md_p = rule_dir / "rule.md"
            if not (json_p.exists() and md_p.exists()):
                continue
            data = json.load(open(json_p, encoding="utf-8"))
            rid = data.get("rule_id", rule_dir.name)
            m = re.search(r"rule_(\d+)", rid)
            if not m:
                continue
            rules.append((int(m.group(1)), phan_dir.name, json_p, md_p, data))
    rules.sort(key=lambda r: r[0])
    return rules


# ─── SQL EMITTERS ─────────────────────────────────────────────────────

class SqlBuilder:
    def __init__(self):
        self.lines = []
        self.tenant = esc(CONFIG["tenant_id"]) if CONFIG["tenant_id"] else "NULL"
        self.created_by = esc(CONFIG["created_by"])

    def emit(self, line):
        self.lines.append(line)

    def emit_blank(self):
        self.lines.append("")

    def header(self):
        self.emit("-- Auto-generated SQL load script for Hizashi Sách 02 v1.2 (Phone)")
        self.emit("-- Generated by scripts/gen_sql.py")
        self.emit("-- Run: psql -h <host> -U <user> -d hizashi_db -f load_v1.2.sql")
        self.emit("--")
        self.emit("-- Pre-clean (uncomment if re-loading):")
        self.emit("-- DELETE FROM conversation_lines WHERE created_by='system' AND conversation_id IN (")
        self.emit("--   SELECT id FROM conversations WHERE created_by='system' AND content_type='curriculum_node'");
        self.emit("--   AND content_id IN (SELECT id::text FROM curriculum_node WHERE curriculum_id IN")
        self.emit("--   (SELECT id FROM curricula WHERE title='" + CONFIG["curriculum_title"] + "' AND is_system=true)));")
        self.emit("-- ... (similar for other tables)")
        self.emit("")
        self.emit("BEGIN;")
        self.emit("")
        self.emit("-- Temp ID register (key → id), drops on COMMIT")
        self.emit("CREATE TEMP TABLE _ids (key text PRIMARY KEY, id int NOT NULL) ON COMMIT DROP;")
        self.emit("")

    def footer(self, stats):
        self.emit("")
        self.emit("-- Verify counts")
        self.emit("DO $$ DECLARE v int; BEGIN")
        for tbl, expected in stats.items():
            self.emit(f"  SELECT COUNT(*) INTO v FROM (SELECT * FROM _ids WHERE key LIKE {esc(tbl + '%')}) x;")
            self.emit(f"  RAISE NOTICE 'Inserted {tbl}: %', v;")
        self.emit("END $$;")
        self.emit("")
        self.emit("COMMIT;")
        self.emit("")

    def insert_curriculum(self, intro_vi, intro_jp, total_items):
        self.emit("-- 1. Curriculum")
        cols = ("level, type, title, introduction, introduction_jp, total_items, "
                "category, status, is_system, is_public, free_preview_count, "
                "tenant_id, is_deleted, is_active, created_at, created_by")
        vals = ", ".join([
            esc(CONFIG["level"]),
            esc(CONFIG["type"]),
            esc(CONFIG["curriculum_title"] + " / " + CONFIG["curriculum_title_jp"]),
            esc(intro_vi),
            esc(intro_jp),
            esc(str(total_items)),
            esc(CONFIG["category"]),
            esc("published"),
            esc_bool(CONFIG["is_system"]),
            esc_bool(CONFIG["is_public"]),
            "3",
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"WITH ins AS (INSERT INTO curricula ({cols}) VALUES ({vals}) RETURNING id)")
        self.emit("INSERT INTO _ids (key, id) SELECT 'curriculum', id FROM ins;")
        self.emit_blank()

    def insert_qset(self):
        self.emit("-- 2. Question set (BJT Sách 02)")
        cols = ("name, set_type, level, question_type, category, description, "
                "is_system, is_public, card_count, tenant_id, is_deleted, is_active, "
                "created_at, created_by")
        vals = ", ".join([
            esc(CONFIG["qset_name"]),
            esc("bjt_practice"),
            esc("BJT-J3-J2"),
            esc("multiple_choice"),
            esc(CONFIG["category"]),
            esc("60 câu BJT từ Sách Điện thoại Công Việc"),
            "true",
            "true",
            "60",
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"WITH ins AS (INSERT INTO question_sets ({cols}) VALUES ({vals}) RETURNING id)")
        self.emit("INSERT INTO _ids (key, id) SELECT 'qset', id FROM ins;")
        self.emit_blank()

    def insert_node(self, rule_num, data, chot_jp):
        rid = f"rule_{rule_num:02d}"
        title_vi = data.get("title", {}).get("vi", "")
        title_jp = data.get("title", {}).get("ja", "")
        ctx_vi = data.get("rule_context", {}).get("vi", "")
        ctx_jp = data.get("rule_context", {}).get("ja", "")
        # node_conclusion: dùng chot JP, node_conclusion_jp = same. Hoặc tách:
        # node_conclusion VN = key_phrases[0].sentence_translation nếu có
        kp = data.get("key_phrases", [{}])[0]
        conclusion_vi = kp.get("sentence_translation", "") if kp else None
        conclusion_jp = chot_jp or (kp.get("sentence", "") if kp else None)
        # related_rules → node_extra
        related = data.get("related_rules", [])
        node_extra = json.dumps({"related_rules": related}, ensure_ascii=False) if related else None

        access = "free" if rule_num in CONFIG["free_rules"] else "paid"

        cols = ("curriculum_id, parent_id, node_type, node_title, note_title_jp, "
                "node_definition, node_definition_jp, node_extra, "
                "node_conclusion, node_conclusion_jp, "
                "order_index, access_level, "
                "tenant_id, is_deleted, is_active, created_at, created_by")
        vals = ", ".join([
            "(SELECT id FROM _ids WHERE key='curriculum')",
            "NULL",
            esc("rule"),
            esc(title_vi),
            esc(title_jp),
            esc(ctx_vi),
            esc(ctx_jp),
            esc(node_extra),
            esc(conclusion_vi),
            esc(conclusion_jp),
            str(rule_num),
            esc(access),
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"-- Rule {rule_num:02d}: {title_vi}")
        self.emit(f"WITH ins AS (INSERT INTO curriculum_node ({cols}) VALUES ({vals}) RETURNING id)")
        self.emit(f"INSERT INTO _ids (key, id) SELECT 'node_{rid}', id FROM ins;")

    def insert_conversation_section(self, rule_num, conv, sec_idx):
        """Insert 1 row in conversations + N rows in conversation_lines."""
        rid = f"rule_{rule_num:02d}"
        sec_key = f"conv_{rid}_{conv.get('section', sec_idx)}_{sec_idx}"
        title_vi = conv.get("label_vi", conv.get("section", ""))
        title_jp = conv.get("label_ja", "")
        analysis = conv.get("analysis", {}) or {}
        situation = analysis.get("vi")
        situation_jp = analysis.get("ja")

        cols = ("user_id, is_single_line, content_type, content_id, level, "
                "title, title_jp, situation, situation_jp, order_index, "
                "is_system, tenant_id, is_deleted, is_active, created_at, created_by")
        vals = ", ".join([
            "NULL",
            "false",
            esc("curriculum_node"),
            f"(SELECT id::text FROM _ids WHERE key='node_{rid}')",
            esc(CONFIG["level"]),
            esc(title_vi),
            esc(title_jp),
            esc(situation),
            esc(situation_jp),
            str(conv.get("display_order", sec_idx + 1)),
            "true",
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"WITH ins AS (INSERT INTO conversations ({cols}) VALUES ({vals}) RETURNING id)")
        self.emit(f"INSERT INTO _ids (key, id) SELECT '{sec_key}', id FROM ins;")

        # Lines
        # Build annotations map: applies_to_line → [annotations]
        ann_map = {}
        for ann in conv.get("annotations", []) or []:
            ann_map.setdefault(ann["applies_to_line"], []).append(ann)

        lines = conv.get("conversation_lines", [])
        if not lines:
            return

        line_cols = ("conversation_id, speaker, speaker_gender, speaker_role, "
                     "sentence, furigana, translation, politeness, order_index, "
                     "notes, notes_jp, "
                     "tenant_id, is_deleted, is_active, created_at, created_by")
        line_vals = []
        for i, ln in enumerate(lines):
            anns = ann_map.get(ln.get("line_id", ""), [])
            note_vi = " || ".join([f"[{a.get('highlight_text','')}] {a.get('vi','')}" for a in anns]) or None
            note_jp = " || ".join([f"[{a.get('highlight_text','')}] {a.get('ja','')}" for a in anns]) or None

            v = "(" + ", ".join([
                f"(SELECT id FROM _ids WHERE key='{sec_key}')",
                esc(ln.get("speaker", "")),
                esc(ln.get("gender")),
                esc(ln.get("speaker_role")),
                esc(ln.get("sentence", "")),
                esc(ln.get("sentence_furigana")),
                esc(ln.get("sentence_translation")),
                esc(ln.get("tone")),
                str(i),
                esc(note_vi),
                esc(note_jp),
                self.tenant,
                "false",
                "true",
                "now()",
                self.created_by,
            ]) + ")"
            line_vals.append(v)

        self.emit(f"INSERT INTO conversation_lines ({line_cols}) VALUES")
        self.emit(",\n".join("  " + v for v in line_vals) + ";")

        # Junction
        self.emit(f"INSERT INTO curriculum_node_content (curriculum_node_id, content_type, content_id, order_index, "
                  f"tenant_id, is_deleted, is_active, created_at, created_by) VALUES "
                  f"((SELECT id FROM _ids WHERE key='node_{rid}'), 'conversation', "
                  f"(SELECT id::text FROM _ids WHERE key='{sec_key}'), {conv.get('display_order', sec_idx+1)}, "
                  f"{self.tenant}, false, true, now(), {self.created_by});")

    def insert_keyphrase(self, rule_num, kp, idx):
        """Each key_phrase → 1 conversation (is_single_line=true) + 1 line."""
        rid = f"rule_{rule_num:02d}"
        key = f"kp_{rid}_{idx}"
        purpose = kp.get("purpose", "")

        cols = ("user_id, is_single_line, content_type, content_id, "
                "title, title_jp, sentence, translation, order_index, "
                "is_system, tenant_id, is_deleted, is_active, created_at, created_by")
        vals = ", ".join([
            "NULL",
            "true",
            esc("curriculum_node"),
            f"(SELECT id::text FROM _ids WHERE key='node_{rid}')",
            esc("Câu chốt: " + purpose),
            esc(purpose),
            esc(kp.get("sentence")),
            esc(kp.get("sentence_translation")),
            str(idx),
            "true",
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"WITH ins AS (INSERT INTO conversations ({cols}) VALUES ({vals}) RETURNING id)")
        self.emit(f"INSERT INTO _ids (key, id) SELECT '{key}', id FROM ins;")

        # 1 line
        line_cols = ("conversation_id, speaker, sentence, translation, "
                     "order_index, tenant_id, is_deleted, is_active, created_at, created_by")
        line_vals = ", ".join([
            f"(SELECT id FROM _ids WHERE key='{key}')",
            esc(kp.get("speaker", "")),
            esc(kp.get("sentence")),
            esc(kp.get("sentence_translation")),
            "0",
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"INSERT INTO conversation_lines ({line_cols}) VALUES ({line_vals});")

        # Junction
        self.emit(f"INSERT INTO curriculum_node_content (curriculum_node_id, content_type, content_id, order_index, "
                  f"tenant_id, is_deleted, is_active, created_at, created_by) VALUES "
                  f"((SELECT id FROM _ids WHERE key='node_{rid}'), 'key_phrase', "
                  f"(SELECT id::text FROM _ids WHERE key='{key}'), {idx + 100}, "  # offset to avoid clash with conv order
                  f"{self.tenant}, false, true, now(), {self.created_by});")

    def insert_question(self, rule_num, q, idx):
        rid = f"rule_{rule_num:02d}"
        qkey = f"q_{rid}_{idx}"
        level = q.get("level", "J3")
        diff = DIFF_MAP.get(level, 3)

        cols = ("user_id, is_system, question_type, content_type, level, "
                "question, sentence, sentence_translation, general_explanation, "
                "selection_type, base_difficulty, skill_category, "
                "tenant_id, is_deleted, is_active, created_at, created_by")
        explanation = q.get("explanation", {}) or {}
        gen_exp = ""
        if explanation.get("vi") or explanation.get("ja"):
            gen_exp = (explanation.get("vi", "") or "") + "\n---\n" + (explanation.get("ja", "") or "")
        vals = ", ".join([
            "NULL",
            "true",
            esc("multiple_choice"),
            esc("curriculum_node"),
            esc(level),
            esc(q.get("question_ja")),
            esc(q.get("question_ja")),
            "NULL",
            esc(gen_exp.strip()),
            esc("single"),
            str(diff),
            esc(q.get("skill")),
            self.tenant,
            "false",
            "true",
            "now()",
            self.created_by,
        ])
        self.emit(f"WITH ins AS (INSERT INTO questions ({cols}) VALUES ({vals}) RETURNING id)")
        self.emit(f"INSERT INTO _ids (key, id) SELECT '{qkey}', id FROM ins;")

        # Answers
        opts = q.get("options", [])
        correct = q.get("correct", "A")
        ans_cols = ('question_id, sentence, is_correct, "order"')
        ans_vals = []
        for i, opt in enumerate(opts):
            is_correct = (chr(65 + i) == correct)
            ans_vals.append("(" + ", ".join([
                f"(SELECT id FROM _ids WHERE key='{qkey}')",
                esc(opt),
                esc_bool(is_correct),
                str(i),
            ]) + ")")
        if ans_vals:
            self.emit(f"INSERT INTO questions_answers ({ans_cols}) VALUES")
            self.emit(",\n".join("  " + v for v in ans_vals) + ";")

        # content_questions: link rule node ↔ question
        self.emit(f"INSERT INTO content_questions (content_type, content_id, question_id, order_index, "
                  f"tenant_id, is_deleted, is_active, created_at, created_by) VALUES "
                  f"('curriculum_node', (SELECT id FROM _ids WHERE key='node_{rid}'), "
                  f"(SELECT id FROM _ids WHERE key='{qkey}'), {idx}, "
                  f"{self.tenant}, false, true, now(), {self.created_by});")

        # question_set_questions: link to BJT set
        self.emit(f"INSERT INTO question_set_questions (question_set_id, question_id, order_index) VALUES "
                  f"((SELECT id FROM _ids WHERE key='qset'), "
                  f"(SELECT id FROM _ids WHERE key='{qkey}'), {rule_num});")

    def insert_vocab_dedup(self, vocab_master, rule_vocab_links):
        """vocab_master: dict kanji → (yomi, meaning). rule_vocab_links: list of (rule_num, kanji, order)."""
        if not vocab_master:
            return
        self.emit("-- Vocabulary (dedup theo kanji)")
        cols = ("level, lemma, kana, meaning, type, is_system, "
                "kanji_count, difficulty, "
                "tenant_id, is_deleted, is_active, created_at, created_by")
        vocab_keys = list(vocab_master.keys())
        vals_list = []
        for kanji in vocab_keys:
            yomi, meaning = vocab_master[kanji]
            kanji_count = sum(1 for c in kanji if '\u4e00' <= c <= '\u9fff')
            v = "(" + ", ".join([
                esc("BJT-business"),
                esc(kanji),
                esc(yomi),
                esc(meaning),
                esc("phone_business"),
                "true",
                str(kanji_count),
                "1",
                self.tenant,
                "false",
                "true",
                "now()",
                self.created_by,
            ]) + ")"
            vals_list.append(v)

        # Insert all vocab and capture ids
        self.emit(f"WITH ins AS (INSERT INTO vocabulary ({cols}) VALUES")
        self.emit(",\n".join("  " + v for v in vals_list))
        self.emit("RETURNING id, lemma)")
        self.emit("INSERT INTO _ids (key, id) SELECT 'vocab_' || lemma, id FROM ins;")
        self.emit_blank()

        # Junction
        self.emit("-- Junction node ↔ vocab")
        junc_cols = ("curriculum_node_id, content_type, content_id, order_index, "
                     "tenant_id, is_deleted, is_active, created_at, created_by")
        junc_vals = []
        for rule_num, kanji, order in rule_vocab_links:
            rid = f"rule_{rule_num:02d}"
            junc_vals.append("(" + ", ".join([
                f"(SELECT id FROM _ids WHERE key='node_{rid}')",
                esc("vocabulary"),
                f"(SELECT id::text FROM _ids WHERE key='vocab_{kanji.replace(chr(39), chr(39)*2)}')",
                str(order + 200),  # offset
                self.tenant,
                "false",
                "true",
                "now()",
                self.created_by,
            ]) + ")"
            )
        if junc_vals:
            self.emit(f"INSERT INTO curriculum_node_content ({junc_cols}) VALUES")
            self.emit(",\n".join("  " + v for v in junc_vals) + ";")
        self.emit_blank()


# ─── MAIN ─────────────────────────────────────────────────────────────

def main():
    rules = find_rules()
    print(f"Found {len(rules)} rules")

    # Read front matter
    fm_path = NOI_DUNG / "_front_matter.md"
    fm_text = fm_path.read_text(encoding="utf-8") if fm_path.exists() else ""
    intro_vi = fm_text  # store full markdown
    intro_jp = ""  # could split, but keep as one for now

    sb = SqlBuilder()
    sb.header()
    sb.insert_curriculum(intro_vi, intro_jp, len(rules))
    sb.insert_qset()

    # Vocab dedup map
    vocab_master = OrderedDict()  # kanji → (yomi, meaning)
    rule_vocab_links = []          # list of (rule_num, kanji, order_idx)

    for rule_num, phan, json_p, md_p, data in rules:
        chot_jp, vocabs = parse_rule_md(md_p)

        # Insert curriculum_node
        sb.insert_node(rule_num, data, chot_jp)

        # Conversations sections (good/bad/variant)
        for sec_idx, conv in enumerate(data.get("conversations", [])):
            sb.insert_conversation_section(rule_num, conv, sec_idx)

        # Key phrases
        for kp_idx, kp in enumerate(data.get("key_phrases", [])):
            sb.insert_keyphrase(rule_num, kp, kp_idx)

        # BJT questions
        for q_idx, q in enumerate(data.get("bjt_practice", [])):
            sb.insert_question(rule_num, q, q_idx)

        # Vocab — dedup
        for v_idx, (kanji, yomi, meaning) in enumerate(vocabs):
            if kanji not in vocab_master:
                vocab_master[kanji] = (yomi, meaning)
            rule_vocab_links.append((rule_num, kanji, v_idx))

        sb.emit_blank()

    # Insert all vocab (after all rules to preserve dedup order)
    sb.insert_vocab_dedup(vocab_master, rule_vocab_links)

    # Footer
    sb.footer({"all": "done"})

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(sb.lines), encoding="utf-8")
    print(f"\n✓ SQL written to: {OUTPUT}")
    print(f"  Lines: {len(sb.lines)}")
    print(f"  Rules: {len(rules)}")
    print(f"  Vocab unique: {len(vocab_master)}")
    print(f"  Vocab links: {len(rule_vocab_links)}")
    print(f"\nRun:\n  PGPASSWORD=admin123 psql -h localhost -U admin -d hizashi_db -f {OUTPUT.relative_to(ROOT.parent.parent)}")


if __name__ == "__main__":
    main()
