-- Bảng tra class theo header — TỰ SINH bởi analyze_tables.py
-- (reset_colwidth.lua require file này). KHÔNG sửa tay.
return {
  { cols=4, header="#|Nguyên tắc (Tiếng Nhật)|Romaji|Nghĩa", cls="t-tbl-57e4ed" },
  { cols=4, header="#|Tiếng Nhật|Romaji|Nghĩa", cls="t-tbl-25b2f7" },
  { cols=5, header="#|Tiếng Nhật|Romaji|Tiếng Việt|Có trong gì", cls="t-tbl-aafcfe" },
  { cols=2, header="Bình thường|Khẩn cấp", cls="t-b-nh-th-ng-1b2a3d" },
  { cols=3, header="Bình thường|Sonkeigo (sếp làm)|Kenjougo (mình làm)", cls="t-b-nh-th-ng-d35db8" },
  { cols=2, header="Bình thường|お~いたします", cls="t-b-nh-th-ng-043624" },
  { cols=2, header="Bình thường|させていただきます", cls="t-b-nh-th-ng-f66c38" },
  { cols=2, header="Bình thường|ております", cls="t-b-nh-th-ng-999a93" },
  { cols=3, header="Bước|Nội dung|Vai trò Hoa", cls="t-b-c-5c09c3" },
  { cols=2, header="Bước|TTS làm gì", cls="t-b-c-ec594c" },
  { cols=3, header="Bước|Việc làm|Thời gian", cls="t-b-c-0b98c1" },
  { cols=4, header="Bước|Việc làm|Thời gian|Lý do", cls="t-b-c-a98d35" },
  { cols=4, header="Chữ|Romaji|Nghĩa|Ví dụ", cls="t-ch-5da177" },
  { cols=4, header="Chữ|Romaji|Nghĩa|Ví dụ ở nhà máy", cls="t-ch-7c6318" },
  { cols=4, header="Chữ|Romaji|Đầy đủ|Nghĩa", cls="t-ch-03ba97" },
  { cols=2, header="Cuộc họp|Khuyến nghị", cls="t-cu-c-h-p-cd3e39" },
  { cols=2, header="Cách nói SAI|Cách nói ĐÚNG", cls="t-c-ch-n-i-sai-27f146" },
  { cols=3, header="Câu hỏi|Tiếng Nhật|Nội dung", cls="t-c-u-h-i-f416cd" },
  { cols=2, header="Câu thường|Sonkeigo / Kenjougo", cls="t-c-u-th-ng-c9a31a" },
  { cols=3, header="Cảm xúc|Thân mật|Lịch sự", cls="t-c-m-x-c-919e19" },
  { cols=2, header="Cấm|Lý do", cls="t-c-m-4a2d14" },
  { cols=3, header="Cấp|Tiếng Nhật|Cường độ", cls="t-c-p-117950" },
  { cols=3, header="Cấp|Tiếng Nhật|Khi dùng", cls="t-c-p-fc86c7" },
  { cols=3, header="Cấp độ|Tiếng Nhật|Tiếng Việt", cls="t-c-p-50c167" },
  { cols=3, header="Cấp độ|Ví dụ|Khi dùng", cls="t-c-p-519a72" },
  { cols=2, header="Cụm|Vai trò", cls="t-c-m-6f7f23" },
  { cols=5, header="Dòng|Câu gốc (rút gọn)|Từ Anh|Gợi ý Tiếng Việt|Lý do", cls="t-d-ng-039f6b" },
  { cols=3, header="Formal|Casual nam|Casual nữ", cls="t-formal-dad623" },
  { cols=4, header="Hạng|Tên|Thời hạn|Đặc điểm", cls="t-h-ng-aebd3a" },
  { cols=5, header="Issue|Linguist|Pedagogue|Domain|Severity", cls="t-issue-914f7e" },
  { cols=3, header="Item|Count|Expected", cls="t-item-07772a" },
  { cols=4, header="Kanji|Hiragana|Romaji|Nghĩa", cls="t-kanji-9c16c6" },
  { cols=3, header="Kanji|Romaji|Nghĩa", cls="t-kanji-696bd9" },
  { cols=3, header="Khoản|Tiếng Việt|Số tiền", cls="t-kho-n-05991d" },
  { cols=3, header="Loại|Mục đích|Ví dụ", cls="t-lo-i-a23e57" },
  { cols=3, header="Loại|Nhiệt độ|Sản phẩm", cls="t-lo-i-f8f6d4" },
  { cols=3, header="Loại|Số nhịp|Khi dùng", cls="t-lo-i-aab7db" },
  { cols=3, header="Loại|Tiếng Nhật|Ví dụ", cls="t-lo-i-8d2a08" },
  { cols=3, header="Loại thanh tra|Tiếng Nhật|Người làm", cls="t-lo-i-thanh-t-dc2201" },
  { cols=6, header="Module|Folder|LyThuyet.md|BaiTap.json|Mogishiken.json|Status", cls="t-module-88aa28" },
  { cols=3, header="Module|Section IDs|Tổng", cls="t-module-4fdba8" },
  { cols=2, header="Màu|Loại", cls="t-m-u-6f0a3f" },
  { cols=2, header="Mẹo|Nội dung", cls="t-m-o-407177" },
  { cols=2, header="Mục|Nội dung", cls="t-m-c-daf95f" },
  { cols=3, header="Mức|Tiếng Nhật|Hậu quả", cls="t-m-c-5aaaea" },
  { cols=4, header="Mức|Tiếng Nhật|Mức nguy hiểm|Ví dụ", cls="t-m-c-2a4e32" },
  { cols=2, header="Nguồn phát hiện|Tỉ lệ", cls="t-ngu-n-ph-t-h-40afc8" },
  { cols=4, header="Nhóm|Tiếng Nhật|Romaji|Mục đích", cls="t-nh-m-5cd821" },
  { cols=3, header="Severity|Count|Status", cls="t-severity-8f1307" },
  { cols=4, header="Table|Expected|Actual|Match?", cls="t-table-cef677" },
  { cols=3, header="Thuật ngữ|Romaji|Nghĩa", cls="t-thu-t-ng-597397" },
  { cols=2, header="Tháng|Bài học cốt lõi", cls="t-th-ng-53cf20" },
  { cols=3, header="Tháng|Chương|Nội dung", cls="t-th-ng-9beacd" },
  { cols=3, header="Thời gian|Hoạt động|Vai trò TTS", cls="t-th-i-gian-2b55ee" },
  { cols=2, header="Thời gian|Nội dung", cls="t-th-i-gian-2067fd" },
  { cols=3, header="Thời gian|Nội dung|Vai trò", cls="t-th-i-gian-19ff9a" },
  { cols=3, header="Tiêu chí|ISO 22000|FSSC 22000", cls="t-ti-u-ch-b6154f" },
  { cols=3, header="Tiêu chí|Sekininsha|HACCP Coord", cls="t-ti-u-ch-56509d" },
  { cols=3, header="Tiêu chí|技能実習 (cũ)|育成就労 (mới)", cls="t-ti-u-ch-395572" },
  { cols=2, header="Tiếng Nhật|Nghĩa", cls="t-ti-ng-nh-t-9551f2" },
  { cols=3, header="Tiếng Nhật|Nghĩa|Khi dùng", cls="t-ti-ng-nh-t-8b1f81" },
  { cols=4, header="Tiếng Nhật|Romaji|Cấp độ|Khi dùng", cls="t-ti-ng-nh-t-68209d" },
  { cols=3, header="Tiếng Nhật|Romaji|Nghĩa", cls="t-ti-ng-nh-t-afdc9a" },
  { cols=3, header="Tiếng Nhật|Romaji|Tiếng Việt", cls="t-ti-ng-nh-t-b83be5" },
  { cols=2, header="Tiếng Nhật|Tiếng Việt", cls="t-ti-ng-nh-t-f7f1d4" },
  { cols=3, header="Tiếng Saitama|Tiếng chuẩn|Nghĩa", cls="t-ti-ng-saitam-f50896" },
  { cols=4, header="Tài liệu đối thủ|Strengths|Weaknesses|Hizashi 11 có thể khác", cls="t-t-i-li-u-i-t-1d66de" },
  { cols=2, header="Tình huống|Cụm", cls="t-t-nh-hu-ng-7c345c" },
  { cols=3, header="Tình huống|Cụm tiếng Nhật|Tiếng Việt", cls="t-t-nh-hu-ng-020ef5" },
  { cols=2, header="Tình huống|Liên hệ", cls="t-t-nh-hu-ng-f62eee" },
  { cols=3, header="Vai|Vai|Xuất hiện", cls="t-vai-114411" },
  { cols=3, header="Vi khuẩn|Triệu chứng|Hậu quả", cls="t-vi-khu-n-8029b6" },
  { cols=3, header="Viết tắt|Dạng đầy đủ|Nghĩa tiếng Việt", cls="t-vi-t-t-t-1f9af5" },
  { cols=2, header="Vấn đề|KAIZEN đơn giản", cls="t-v-n-8e5ec0" },
  { cols=3, header="Vị trí|Tên|Ai ngồi", cls="t-v-tr-28ba49" },
  { cols=3, header="Đối tượng|Cách chào|Cấp độ", cls="t-i-t-ng-ac354e" },
}
