-- Bảng tra class theo header — TỰ SINH bởi analyze_tables.py
-- (reset_colwidth.lua require file này). KHÔNG sửa tay.
return {
  { cols=3, header="|Công ty mình|Công ty người khác", cls="t-tbl-c16c8f" },
  { cols=3, header="|Khi nói về công ty MÌNH|Khi nói về công ty NGƯỜI KHÁC", cls="t-tbl-391bfd" },
  { cols=3, header="|いただく + Vật|いただく + て形", cls="t-tbl-20eaa4" },
  { cols=3, header="|させていただく|させられる", cls="t-tbl-b0eeb8" },
  { cols=3, header="|させてもらう|させられる", cls="t-tbl-8ba148" },
  { cols=3, header="|させてもらえますか|してもらえますか", cls="t-tbl-e88269" },
  { cols=3, header="|てあげる|させる", cls="t-tbl-4d2440" },
  { cols=3, header="|てもらう|られる (受動)", cls="t-tbl-f12095" },
  { cols=3, header="|に|によって", cls="t-tbl-f2cf04" },
  { cols=2, header="Bình thường|Kính ngữ", cls="t-b-nh-th-ng-3a8e3e" },
  { cols=3, header="Cách nói|Câu|Sắc thái", cls="t-c-ch-n-i-74383c" },
  { cols=3, header="Câu|Ai quyết định|Sắc thái", cls="t-c-u-6ebad9" },
  { cols=3, header="Câu|Cấu trúc|Nghĩa", cls="t-c-u-b59563" },
  { cols=2, header="Câu|Loại kính ngữ", cls="t-c-u-e2b02a" },
  { cols=2, header="Câu|Nghĩa", cls="t-c-u-cc713e" },
  { cols=3, header="Câu|Nghĩa|Sắc thái", cls="t-c-u-410006" },
  { cols=3, header="Câu|Nghĩa|Đúng/Sai trong kinh doanh", cls="t-c-u-e1b00f" },
  { cols=2, header="Câu|Phân tích", cls="t-c-u-b2cb18" },
  { cols=3, header="Câu|Phân tích|Ai là trung tâm", cls="t-c-u-829795" },
  { cols=4, header="Cấu trúc|Ai làm|Ví dụ|Nghĩa", cls="t-c-u-tr-c-aae864" },
  { cols=5, header="Cấu trúc|Ký hiệu|Ai làm|Ai nhận lợi|Sắc thái", cls="t-c-u-tr-c-ca93e9" },
  { cols=3, header="Cấu trúc|Nghĩa|Góc nhìn", cls="t-c-u-tr-c-f52cc4" },
  { cols=4, header="Cặp|Câu sai|Câu đúng|Lý do", cls="t-c-p-6b4cd4" },
  { cols=3, header="Cặp dễ nhầm|Cấu trúc 1|Cấu trúc 2", cls="t-c-p-d-nh-m-d165a4" },
  { cols=2, header="Cụm từ|Nghĩa", cls="t-c-m-t-7825b9" },
  { cols=3, header="Cụm từ|Nghĩa|Ghi chú", cls="t-c-m-t-27ec6b" },
  { cols=2, header="Cụm từ|Sắc thái", cls="t-c-m-t-a36533" },
  { cols=5, header="Dòng|Câu gốc (rút gọn)|Từ Anh|Gợi ý Tiếng Việt|Lý do", cls="t-d-ng-039f6b" },
  { cols=3, header="Hành động|Nhóm mình làm (謙譲語)|Nhóm kia làm (尊敬語)", cls="t-h-nh-ng-57bf27" },
  { cols=4, header="Lỗi|Câu sai|Câu đúng|Lý do", cls="t-l-i-ca9ade" },
  { cols=2, header="Mẹo|Nội dung", cls="t-m-o-407177" },
  { cols=2, header="Mục|Nội dung", cls="t-m-c-daf95f" },
  { cols=4, header="Nghĩa|Tên|Ví dụ|Dấu hiệu", cls="t-ngh-a-f0f633" },
  { cols=4, header="Nghĩa|Tên|Ví dụ|Dấu hiệu nhận biết", cls="t-ngh-a-d86571" },
  { cols=2, header="Nguyên thể|Bị động", cls="t-nguy-n-th-3f99b5" },
  { cols=3, header="Nguyên thể|Cột a|Bị động", cls="t-nguy-n-th-06d14f" },
  { cols=2, header="Nguyên thể|Sai khiến", cls="t-nguy-n-th-3fe8e8" },
  { cols=3, header="Nguyên thể|Sai khiến|Sai khiến bị động", cls="t-nguy-n-th-c9cbb4" },
  { cols=2, header="Nguyên thể|Sai khiến bị động", cls="t-nguy-n-th-ef527e" },
  { cols=3, header="Nguyên thể|Đầy đủ|Rút gọn", cls="t-nguy-n-th-a833d9" },
  { cols=3, header="Người|Nhóm mình (khi nói với Soto)|Nhóm kia", cls="t-ng-i-fbb41a" },
  { cols=2, header="Ngữ cảnh|Câu đúng", cls="t-ng-c-nh-77fd60" },
  { cols=3, header="Ngữ cảnh|Uchi|Soto", cls="t-ng-c-nh-e01f94" },
  { cols=2, header="Phần|Nội dung", cls="t-ph-n-e3d3f3" },
  { cols=3, header="Phần email|Uchi/Soto|Cách dùng", cls="t-ph-n-email-2d26b1" },
  { cols=2, header="SAI (Dùng Sonkeigo cho người trong nhóm)|ĐÚNG (Dùng Kenjougo)", cls="t-sai-d-ng-son-11df57" },
  { cols=2, header="SOTO (外) — Người ngoài nhóm|UCHI (内) — Người trong nhóm", cls="t-soto-ng-i-ng-db7091" },
  { cols=2, header="Thông thường (Thân mật)|Teineigo (Lịch sự)", cls="t-th-ng-th-ng--f85869" },
  { cols=3, header="Thể|Câu|Nghĩa", cls="t-th-4a3a84" },
  { cols=2, header="Thể|Dạng", cls="t-th-28b70b" },
  { cols=4, header="Thể|Người/vật|Trợ từ|Ghi chú", cls="t-th-42ed41" },
  { cols=4, header="Thể|Tên|Cấu trúc cơ bản|Ngữ nghĩa cốt lõi", cls="t-th-3defa2" },
  { cols=4, header="Tiêu chí|尊敬語 Sonkeigo|謙譲語 Kenjougo|丁寧語 Teineigo", cls="t-ti-u-ch-0c5221" },
  { cols=2, header="Tiếng Nhật|Nghĩa", cls="t-ti-ng-nh-t-9551f2" },
  { cols=3, header="Tiếng Nhật|Nghĩa|Mức độ", cls="t-ti-ng-nh-t-d8c18d" },
  { cols=3, header="Trợ từ|Dùng khi nào|Ví dụ", cls="t-tr-t-f02d3e" },
  { cols=4, header="Trợ từ|Nghĩa|Ví dụ|Ghi chú", cls="t-tr-t-5ef793" },
  { cols=3, header="Tình huống|Cách nói (đúng)|Lỗi thường gặp", cls="t-t-nh-hu-ng-cae73f" },
  { cols=2, header="Tình huống|Câu", cls="t-t-nh-hu-ng-6ea8d6" },
  { cols=3, header="Tình huống|Câu|Đúng/Sai", cls="t-t-nh-hu-ng-e78b54" },
  { cols=2, header="Tình huống|Câu nói", cls="t-t-nh-hu-ng-a190f2" },
  { cols=4, header="Tình huống|Câu sai|Câu đúng|Lỗi vi phạm", cls="t-t-nh-hu-ng-0321c9" },
  { cols=3, header="Tình huống|Câu đúng|Lý do", cls="t-t-nh-hu-ng-4c2445" },
  { cols=4, header="Tình huống|もらう|いただく|Lựa chọn tốt hơn", cls="t-t-nh-hu-ng-f59dd4" },
  { cols=3, header="Từ thông thường|Dạng Kenjougo|Nghĩa", cls="t-t-th-ng-th-n-edff9a" },
  { cols=3, header="Từ thông thường|Dạng Sonkeigo|Nghĩa", cls="t-t-th-ng-th-n-83ef7c" },
  { cols=3, header="Vai trò|Nói về người trong công ty mình (với người ngoài)|Nói về/với người công ty khác", cls="t-vai-tr-f0ef9f" },
  { cols=3, header="Viết tắt|Dạng đầy đủ|Nghĩa tiếng Việt", cls="t-vi-t-t-t-1f9af5" },
  { cols=2, header="Ví dụ|Nghĩa", cls="t-v-d-7c78d4" },
  { cols=3, header="Đang nói chuyện với|Uchi (nhóm mình)|Soto (nhóm kia)", cls="t-ang-n-i-chuy-223495" },
  { cols=4, header="Động từ|Cấp độ|Chiều hướng hành động|Ai là chủ thể", cls="t-ng-t-741bff" },
  { cols=4, header="Động từ thường|Nghĩa|Dạng Kenjougo|Ghi chú", cls="t-ng-t-th-ng-c17992" },
  { cols=4, header="Động từ thường|Nghĩa|Dạng Sonkeigo|Ghi chú", cls="t-ng-t-th-ng-b79540" },
  { cols=2, header="させてもらう|させられる", cls="t-tbl-0c67e2" },
}
