-- Bảng tra class theo header — TỰ SINH bởi analyze_tables.py
-- (reset_colwidth.lua require file này). KHÔNG sửa tay.
return {
  { cols=3, header="|Ghi chú|Chi tiết", cls="t-tbl-3236fa" },
  { cols=3, header="|Giờ|Hành động", cls="t-tbl-817077" },
  { cols=3, header="|Việc làm|Chi tiết", cls="t-tbl-fb0263" },
  { cols=4, header="#|Chủ đề|Câu mở chuẩn|Câu đào sâu", cls="t-tbl-e03fd5" },
  { cols=4, header="#|Chủ đề|Mức nguy|Câu né khéo", cls="t-tbl-a5da65" },
  { cols=4, header="#|Chủ đề NG|Lý do|Mức độ", cls="t-tbl-57a959" },
  { cols=5, header="#|Nguồn|Địa chỉ/Ứng dụng|Tần suất|Ghi chú", cls="t-tbl-144fba" },
  { cols=4, header="Cấp|Mức quan hệ|Chủ đề an toàn|Ví dụ khách", cls="t-c-p-83c9ef" },
  { cols=3, header="Giờ|Hành động|Chi tiết", cls="t-gi-3e1444" },
  { cols=2, header="Hạng mục|Nội dung", cls="t-h-ng-m-c-bf2de7" },
  { cols=3, header="Loại|Tín hiệu|Phản ứng đúng", cls="t-lo-i-ade00e" },
  { cols=4, header="Lớp|Tên|Khi nào dùng|Câu mẫu", cls="t-l-p-4427b4" },
  { cols=2, header="Mục|Nội dung", cls="t-m-c-daf95f" },
  { cols=3, header="Mức|Công thức|Ví dụ", cls="t-m-c-43adb8" },
  { cols=2, header="Nguồn|Lý do", cls="t-ngu-n-5030c5" },
  { cols=3, header="Phần|Tên|Nội dung", cls="t-ph-n-be6b11" },
  { cols=3, header="Thế hệ|Sinh năm|Bài 鉄板 (nhạc Showa / J-pop)", cls="t-th-h-fff37b" },
  { cols=4, header="Tình huống|Mẫu câu Nhật|Nghĩa Việt|Cách dùng", cls="t-t-nh-hu-ng-c0d21b" },
  { cols=5, header="Từ|Cách đọc|Hán Việt|Nghĩa|Rule", cls="t-t-7a9849" },
  { cols=3, header="Từ chuyển|Sắc thái|Khi dùng", cls="t-t-chuy-n-2ee3d0" },
  { cols=2, header="Vai|Câu (TỐT)", cls="t-vai-72b08b" },
  { cols=2, header="Vai|Câu (bản ĐÚNG)", cls="t-vai-adad25" },
  { cols=3, header="Yếu tố|Ghi gì|Khi nào hỏi lại", cls="t-y-u-t-17e51c" },
  { cols=3, header="Đội|県|Giải đấu", cls="t-i-2382b9" },
  { cols=1, header="お遍路 88ヶ所", cls="t-88-8aed4a" },
  { cols=6, header="日付|場所|トピック|Thông tin mới|Không khí|Câu mở lần sau", cls="t-tbl-b6b11a" },
  { cols=6, header="県|Tỉnh lỵ|Đặc sản|Sake/酒|Lễ hội biểu tượng|Du lịch", cls="t-tbl-1e6cc1" },
  { cols=6, header="県|県庁|名物|観光|祭り|Thể thao", cls="t-tbl-c8bf5a" },
  { cols=6, header="県|都市|名物|スポーツ|祭り|一言", cls="t-tbl-5a29a7" },
}
